version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME?Set DB_NAME environment variable}
      POSTGRES_USER: ${DB_USER?Set DB_USER environment variable}
      POSTGRES_PASSWORD: ${DB_PASSWORD?Set DB_PASSWORD environment variable}
      MYSQL_PORT: ${DB_PORT-5432}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      # Для доступа с хоста
      - 5432:${DB_PORT}

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: app
    depends_on:
      - db
    #restart: always
    environment:
      DB_HOST: 'db' # Не менять! Должно совпадать с названием сервиса БД в этом файле
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME?Set DB_NAME environment variable}
      DB_USER: ${DB_USER?Set DB_USER environment variable}
      DB_PASSWORD: ${DB_PASSWORD?Set DB_PASSWORD environment variable}
      SESSION_SECRET: ${SESSION_SECRET?Set SESSION_SECRET environment variable}
      WAIT_HOSTS: db:${DB_PORT}
    ports:
      - 8080:8080
